SELECT
    YEAR(r.RESERVE_DATE) AS yr,
    MONTH(r.RESERVE_DATE) AS mo,
    SUM(CASE WHEN RTRIM(ISNULL(r.RESERVE_PATH, '')) = 'CTI' THEN 1 ELSE 0 END) AS incall,
    SUM(CASE WHEN RTRIM(ISNULL(r.RESERVE_PATH, '')) = 'CRM' THEN 1 ELSE 0 END) AS outcall,
    SUM(CASE WHEN RTRIM(ISNULL(r.RESERVE_PATH, '')) = 'KAKAO' THEN 1 ELSE 0 END) AS kakao,
    SUM(CASE WHEN RTRIM(ISNULL(r.RESERVE_PATH, '')) = 'NAVER' THEN 1 ELSE 0 END) AS naver,
    SUM(CASE WHEN RTRIM(ISNULL(r.RESERVE_PATH, '')) IN ('ONLINE', 'APP') THEN 1 ELSE 0 END) AS homepage
FROM RESERVATION r WITH(NOLOCK)
WHERE r.RESERVE_DATE >= :from AND r.RESERVE_DATE <= :to
    AND r.RESERVE_STATE <> 'C'
    AND r.RESERVE_FLAG IN ('M', 'H', 'D', 'F')
GROUP BY YEAR(r.RESERVE_DATE), MONTH(r.RESERVE_DATE)
ORDER BY YEAR(r.RESERVE_DATE), MONTH(r.RESERVE_DATE)
