SELECT
    RESERVE_DATE AS date,
    COUNT(*) AS reservations,
    SUM(CASE WHEN RESERVE_FLAG = 'F' THEN 1 ELSE 0 END) AS examinations,
    SUM(CASE WHEN RESERVE_STATE = 'C' THEN 1 ELSE 0 END) AS cancellations
FROM RESERVATION WITH(NOLOCK)
WHERE RESERVE_DATE >= :from AND RESERVE_DATE <= :to
GROUP BY RESERVE_DATE
ORDER BY RESERVE_DATE
