SELECT
    LEFT(RTRIM(START_TIME), 2) + ':00' AS slot,
    COUNT(*) AS count
FROM RESERVATION WITH(NOLOCK)
WHERE RESERVE_DATE >= :from AND RESERVE_DATE <= :to
    AND RESERVE_STATE <> 'C'
    AND START_TIME IS NOT NULL
    AND RTRIM(START_TIME) <> ''
GROUP BY LEFT(RTRIM(START_TIME), 2)
ORDER BY LEFT(RTRIM(START_TIME), 2)
