SELECT
    YEAR(r.RESERVE_DATE) AS yr,
    MONTH(r.RESERVE_DATE) AS mo,
    SUM(CASE WHEN r.RESERVE_FLAG = 'O' THEN 1 ELSE 0 END) AS surgery,
    SUM(CASE WHEN r.RESERVE_JINRYO = '2' THEN 1 ELSE 0 END) AS outpatient,
    SUM(CASE WHEN r.RESERVE_FLAG = 'D' THEN 1 ELSE 0 END) AS dreamlens
FROM RESERVATION r WITH(NOLOCK)
WHERE r.RESERVE_DATE >= :from AND r.RESERVE_DATE <= :to
    AND r.RESERVE_STATE <> 'C'
GROUP BY YEAR(r.RESERVE_DATE), MONTH(r.RESERVE_DATE)
ORDER BY YEAR(r.RESERVE_DATE), MONTH(r.RESERVE_DATE)
